# Solutions for 100 numpy exercises
Leandro D. Medus
github LeoSf

# 100 numpy exercises

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
#jovian.commit(project='100-numpy-exercises')
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Creating a new project "leosf/week3_ntk2_100-numpy-exercises"
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [2]:
# Ucomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print("numpy version: " + np.__version__ + "\n\n")

print("""
Current configuration:
----------------------""")
print(np.show_config())

numpy version: 1.14.0



Current configuration:
----------------------
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Programas/Microsoft Visual Studio/Shared/Anaconda3_64\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Programas/Microsoft Visual Studio/Shared/Anaconda3_64\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Programas/Microsoft Visual Studio/Shared/Anaconda3_64\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWT

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
vec = np.zeros(10)
print(len(vec))
print(type(vec))

10
<class 'numpy.ndarray'>


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
print(np.size(vec))
print((vec.itemsize))

print("Total size of the container: {} bytes".format(np.size(vec) * vec.itemsize))

10
8
Total size of the container: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
# from terminal 
# python -c "import numpy as np; np.info(np.size)"

import os
os.system('python -c "import numpy as np; np.info(np.size)"')

0

the bad thing here is that we only get the return value of the function excecuted

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
vec = np.zeros(10)
vec[4] = 1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
# from 10 to 49 included
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
vec[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
vec[5:1:-1]

array([15, 14, 13, 12])

In [12]:
vec[1:10:2]

array([11, 13, 15, 17, 19])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
vec = np.array([1,2,0,0,4,0])
print(vec)

print("Non-zero elements - indeces: " + str(vec.nonzero()))
print("    Zero elements - indeces: " + str(np.where(vec == 0)))

[1 2 0 0 4 0]
Non-zero elements - indeces: (array([0, 1, 4], dtype=int64),)
    Zero elements - indeces: (array([2, 3, 5], dtype=int64),)


Save your progress by commiting your work to Jovian

In [73]:
import jovian

In [74]:
#jovian.commit(project='numpy-100-exercises')
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
np.random.rand(3,3)

array([[0.30474534, 0.79680043, 0.4507141 ],
       [0.77858637, 0.39579172, 0.79282477],
       [0.23038161, 0.65060631, 0.67819165]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
mat = np.random.randn(10,10)

print(mat)
np.max(mat)

[[-0.30144722 -0.90544928 -0.58111014  0.29070176  1.79295872 -0.42831155
  -1.49393664 -0.18451038  0.36128442 -0.23415361]
 [ 2.78112367 -0.3054343   0.42203596  1.28183339  0.98721713 -0.91556558
  -0.72664699 -0.90514011  1.21270869  0.94297424]
 [ 1.47095166 -0.76649949  1.55194668 -0.25899909  0.67479082 -0.27243267
   0.5844576  -0.29676863  0.65498942 -1.27430283]
 [ 0.22257354 -1.3497808  -1.8816614   0.92848224  1.29990143  0.27104543
   0.23966349 -0.07243425  0.14932817  0.06221398]
 [-0.56648013  0.49835522 -0.40075605 -0.55623177 -1.65252238  0.3685525
   1.24826682 -0.92587679  1.48845041  0.92995642]
 [-0.86232633  0.8453872   0.65776673 -0.75092363 -1.1205374  -1.2518173
   0.12605267  0.0063353  -0.53624907  0.85904184]
 [-1.11240377 -0.09175666 -1.94272646 -0.41686548  1.01047585 -1.2252658
  -0.69225156 -1.25205458 -0.67573108  1.1820192 ]
 [-1.5942987  -1.42081675 -0.36658592  0.4608317  -0.97003442 -0.09017658
   0.41002603 -1.43968852  0.07070815  0.33909859]
 [ 

2.7811236683595553

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
vec = np.random.randn(30)
np.mean(vec)

-0.2881581657056644

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
import numpy as np
mat = np.ones([5,5])
mat[1:-1, 1:-1] = 0

#mat[1:-1, 1:-1] = np.zeros([3,3])
mat

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
# np.concatenate  --> to complex but still valid

np.pad(mat,pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
print( 0 * np.nan                 )
print( np.nan == np.nan           )
print( np.inf > np.nan            )
print( np.nan - np.nan            )
print( np.nan in set([np.nan])    )   
print( 0.3 == 3 * 0.1             )    # flase, problem in comparison with floats due to rounding

print( type(0.3)         )
print( type(3 * 0.1)     )

nan
False
False
nan
True
False
<class 'float'>
<class 'float'>


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [27]:
mat = np.zeros([5,5])

for i in range(4):
    mat[i+1,i] = i+1

print(mat)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [36]:
# the pro way: (this build a matrix with  a specific diagonal)

mat = np.diag(1+np.arange(4),k=-1)
print(mat)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]]


In [42]:
x = np.arange(9).reshape(3,3)
print("Matrix: x")
print(x)

mat = np.diag(x)
print("Printing element from x's diagonal")
print(mat)

mat = np.diag(x, k=1)
print("Printing element from x's diagonal + 1")
print(mat)

mat = np.diag(x, k=-1)
print("Printing element from x's diagonal - 1")
print(mat)

Matrix: x
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Printing element from x's diagonal
[0 4 8]
Printing element from x's diagonal + 1
[1 5]
Printing element from x's diagonal - 1
[3 7]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [57]:
# chessboard style 

mat = np.zeros((8,8), dtype=int)
mat[1::2,::2] = 1
mat[::2,1::2] = 1

print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [66]:
mat = np.arange(6*7*8).reshape(6,7,8)

nx = 6
ny = 7 
nz = 8

print("mat[0,0,0]: {}".format(mat[0,0,0]))
print("mat[0,1,0]: {}".format(mat[0,1,0]))
print("mat[0,2,0]: {}".format(mat[0,2,0]))
print()

n = 100-1
z = n % nz

x = int(np.floor(n / (ny * nz)))
y = int(np.floor((n % (ny * nz)) / nz))

print (x, y , z)
print (mat[x,y,z])

mat[0,0,0]: 0
mat[0,1,0]: 8
mat[0,2,0]: 16

1 5 3
99


In [65]:
# the pro way

z = np.unravel_index(99, (6,7,8))
print(z)

(1, 5, 3)


Save your progress by commiting your work to Jovian

In [67]:
import jovian

<IPython.core.display.Javascript object>

In [68]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [74]:
x = np.array([[0,1],[1,0]])
np.tile(x,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [81]:
mat = np.random.randn(5,5)

print(np.mean(mat))
print(np.std(mat))
print("Close because it's just a few elements")


mat = np.random.randn(500,500)

print(np.mean(mat))
print(np.std(mat))
print("now we are talking")

-0.052122356278250945
0.9004901761568984
Close because it's just a few elements
-0.000335691301142513
1.001069266797396
now we are talking


In [82]:
# normalizing a random matrix

mat = np.random.rand(500,500)

print(np.mean(mat))
print(np.std(mat))
print()


mat = ( mat-np.mean(mat) )/ np.std(mat)
print(np.mean(mat))
print(np.std(mat))

0.5006880189086779
0.28897704097777177

-1.5003820408310275e-16
1.0000000000000002


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [100]:
color = np.dtype([("r", np.ubyte, 1 ),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

# TODO: pending analysis

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [102]:
mat_1 = np.random.randn(5,3)
mat_2 = np.random.randn(3,2)

result_1 = mat_1 @ mat_2
result_2 = np.matmul(mat_1, mat_2)

result_1 == result_2

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [125]:
x = np.floor(np.random.rand(10)*10).astype(int)
print(x)

x2 = np.arange(10)
print(x2)

x[(3 < x) & (x < 8)] *= -1
print(x)

x2[(3 < x2) & (x2 < 8)] *= -1
print(x2)


[7 1 6 6 6 5 1 3 9 2]
[0 1 2 3 4 5 6 7 8 9]
[-7  1 -6 -6 -6 -5  1  3  9  2]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [18]:
# 1. 9

print(sum(range(5),-1))     # ----> 9, ok!
# secod parameter is another number to sum

# from numpy import *
# print(sum(range(5),-1))     # -> 10 wtf
# this overrides sum function

import numpy as np
print(np.sum(range(5),-1))
# secod parameter is axis

print(np.sum([[1,2],[3,4]],0))
print(np.sum([[1,2],[3,4]],1))
print(np.sum([[1,2],[3,4]],-1))
# sumer check

9
10
[4 6]
[3 7]
[3 7]


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [41]:
Z = np.arange(9).astype(int)
print(Z)

print(Z**Z)                 # pow element-wise 
print(2 << Z)               # logical shift. base 2 multiplication
print(2 << Z >> 2)          # after previous step, each number is divided by 4
print(Z <- Z)               # bool comparison Z < -Z
print(1j*Z)                 # converting each number to the imaginary part of a complex number
print(Z/1/1)                # interesting... converting ints to floats because the division involved    
Z<Z>Z                       # error: 2nd operation: compearing bool with ints

[0 1 2 3 4 5 6 7 8]
[       1        1        4       27      256     3125    46656   823543
 16777216]
[  2   4   8  16  32  64 128 256 512]
[  0   1   2   4   8  16  32  64 128]
[False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```


In [44]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [53]:
x = np.random.uniform(-10,+10,10)
print(x)

x[x <0] = np.floor(x[x <0])
x[x >0] = np.ceil(x[x >0])
print(x)

print(np.copysign(np.ceil(np.abs(x)), x))

# More readable but less efficient
print(np.where(x>0, np.ceil(x), np.floor(x)))


[-7.08953612  7.22139107 -8.89378231  7.83660483  4.34563835  4.40093583
  6.15762025 -7.10372816  2.95704917 -6.27984883]
[-8.  8. -9.  8.  5.  5.  7. -8.  3. -7.]
[-8.  8. -9.  8.  5.  5.  7. -8.  3. -7.]
[-8.  8. -9.  8.  5.  5.  7. -8.  3. -7.]


In [77]:
N = 10**8

In [78]:
x = np.random.uniform(-10,+10,N)
print(len(x))

%time x[x <0] = np.floor(x[x <0])
%time x[x >0] = np.ceil(x[x >0])


100000000
Wall time: 2.32 s
Wall time: 2.21 s


In [79]:
x = np.random.uniform(-10,+10,N)
print(len(x))

%time x = np.copysign(np.ceil(np.abs(x)), x)

100000000
Wall time: 2.64 s


In [80]:
x = np.random.uniform(-10,+10,N)
print(len(x))

# More readable but less efficient
%time x=np.where(x>0, np.ceil(x), np.floor(x))

100000000
Wall time: 4.38 s


#### 30. How to find common values between two arrays? (★☆☆)

In [82]:
x1 = np.random.randint(0,10,10)
x2 = np.random.randint(0,10,10)
print(np.intersect1d(x1, x2))

[2 6 8]


Save your progress by commiting your work to Jovian

In [83]:
import jovian

<IPython.core.display.Javascript object>

In [84]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [88]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity (I'm crying hahahahaha)
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

np.arange(3) / 0

array([nan, inf, inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [93]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

False
nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [95]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2020-09-04
2020-09-05
2020-09-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [96]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [109]:
N = 10**8

In [110]:
A = np.ones(N)*1
B = np.ones(N)*2
C = np.ones(N)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5, ..., -1.5, -1.5, -1.5])

In [111]:
def funct_1():
    A = np.ones(N)*1
    B = np.ones(N)*2
    C = np.ones(N)*3
    np.add(A,B,out=B)
    np.divide(A,2,out=A)
    np.negative(A,out=A)
    np.multiply(A,B,out=A)

%time funct_1()

Wall time: 3.65 s


In [112]:
def funct_2():
    A = np.ones(N)*1
    B = np.ones(N)*2
    C = np.ones(N)*3
    A = ((A+B)*(-A/2))

%time funct_2()

Wall time: 5.16 s


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [118]:
#method 1
x = np.random.randn(10) * 10
print(x)
np.trunc(x)

[-22.5399474  -34.42516006  -4.47876689 -15.02363068   3.14744663
   9.49039001   4.10061709  -2.21330653  -7.86887024  -5.1919368 ]


array([-22., -34.,  -4., -15.,   3.,   9.,   4.,  -2.,  -7.,  -5.])

In [120]:
# method 2

print(x)
x.astype(int)


[-22.5399474  -34.42516006  -4.47876689 -15.02363068   3.14744663
   9.49039001   4.10061709  -2.21330653  -7.86887024  -5.1919368 ]


array([-22, -34,  -4, -15,   3,   9,   4,  -2,  -7,  -5])

In [121]:
# method 3


print(x)
x//1

[-22.5399474  -34.42516006  -4.47876689 -15.02363068   3.14744663
   9.49039001   4.10061709  -2.21330653  -7.86887024  -5.1919368 ]


array([-23., -35.,  -5., -16.,   3.,   9.,   4.,  -3.,  -8.,  -6.])

In [ ]:
# pending ... 
# could it be floor and ceil, but is another kind of aproximation like the last one

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [122]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [137]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


yield is a keyword that is used like return, except the function will return a generator.
3rd parameter of from iter is: --count-- int, optional
The number of items to read from iterable. The default is -1, which means all data is read.

In [136]:
# Generators
# Generators are iterators, a kind of iterable you can only iterate over once. Generators do not store all the values in memory, they generate the values on the fly:

mygenerator = (x*x for x in range(3))
for i in mygenerator:
    print(i)

for i in mygenerator:
    print(i)

0
1
4


it is just the same except you used () instead of []. BUT, you cannot perform for i in mygenerator a second time since generators can only be used once: they calculate 0, then forget about it and calculate 1, and end calculating 4, one by one

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [141]:
x = np.random.rand(10)

print(max(x))
print(min(x))

0.9736031416836449
0.015090965238816145


In [145]:
# still valid: linearly spaced samples
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [147]:
x = np.random.rand(10)
print(x)

print(np.sort(x))

print(x)

[0.53244266 0.92488065 0.06826649 0.44808376 0.4465072  0.92961973
 0.96181219 0.76231455 0.55963291 0.25239053]
[0.06826649 0.25239053 0.4465072  0.44808376 0.53244266 0.55963291
 0.76231455 0.92488065 0.92961973 0.96181219]
[0.53244266 0.92488065 0.06826649 0.44808376 0.4465072  0.92961973
 0.96181219 0.76231455 0.55963291 0.25239053]


Save your progress by commiting your work to Jovian

In [148]:
import jovian

In [149]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

Save and commit your work.

In [12]:
import jovian

In [13]:
#jovian.commit()
# jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

Save and commit your work.

In [14]:
import jovian

In [15]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Save and commit your work

In [16]:
import jovian

In [17]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

Save and commit your work.

In [18]:
import jovian

In [19]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

In [20]:
import jovian

In [21]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Save and commit your work

In [22]:
import jovian

In [ ]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100