# Solutions for 100 numpy exercises
Leandro D. Medus
github LeoSf

# 100 numpy exercises

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
#jovian.commit(project='100-numpy-exercises')
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Creating a new project "leosf/week3_ntk2_100-numpy-exercises"
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [2]:
# Ucomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print("numpy version: " + np.__version__ + "\n\n")

print("""
Current configuration:
----------------------""")
print(np.show_config())

numpy version: 1.14.0



Current configuration:
----------------------
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Programas/Microsoft Visual Studio/Shared/Anaconda3_64\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Programas/Microsoft Visual Studio/Shared/Anaconda3_64\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Programas/Microsoft Visual Studio/Shared/Anaconda3_64\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWT

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
vec = np.zeros(10)
print(len(vec))
print(type(vec))

10
<class 'numpy.ndarray'>


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
print(np.size(vec))
print((vec.itemsize))

print("Total size of the container: {} bytes".format(np.size(vec) * vec.itemsize))

10
8
Total size of the container: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
# from terminal 
# python -c "import numpy as np; np.info(np.size)"

import os
os.system('python -c "import numpy as np; np.info(np.size)"')

0

the bad thing here is that we only get the return value of the function excecuted

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
vec = np.zeros(10)
vec[4] = 1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
# from 10 to 49 included
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
vec[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
vec[5:1:-1]

array([15, 14, 13, 12])

In [12]:
vec[1:10:2]

array([11, 13, 15, 17, 19])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
vec = np.array([1,2,0,0,4,0])
print(vec)

print("Non-zero elements - indeces: " + str(vec.nonzero()))
print("    Zero elements - indeces: " + str(np.where(vec == 0)))

[1 2 0 0 4 0]
Non-zero elements - indeces: (array([0, 1, 4], dtype=int64),)
    Zero elements - indeces: (array([2, 3, 5], dtype=int64),)


Save your progress by commiting your work to Jovian

In [73]:
import jovian

In [74]:
#jovian.commit(project='numpy-100-exercises')
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
np.random.rand(3,3)

array([[0.30474534, 0.79680043, 0.4507141 ],
       [0.77858637, 0.39579172, 0.79282477],
       [0.23038161, 0.65060631, 0.67819165]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
mat = np.random.randn(10,10)

print(mat)
np.max(mat)

[[-0.30144722 -0.90544928 -0.58111014  0.29070176  1.79295872 -0.42831155
  -1.49393664 -0.18451038  0.36128442 -0.23415361]
 [ 2.78112367 -0.3054343   0.42203596  1.28183339  0.98721713 -0.91556558
  -0.72664699 -0.90514011  1.21270869  0.94297424]
 [ 1.47095166 -0.76649949  1.55194668 -0.25899909  0.67479082 -0.27243267
   0.5844576  -0.29676863  0.65498942 -1.27430283]
 [ 0.22257354 -1.3497808  -1.8816614   0.92848224  1.29990143  0.27104543
   0.23966349 -0.07243425  0.14932817  0.06221398]
 [-0.56648013  0.49835522 -0.40075605 -0.55623177 -1.65252238  0.3685525
   1.24826682 -0.92587679  1.48845041  0.92995642]
 [-0.86232633  0.8453872   0.65776673 -0.75092363 -1.1205374  -1.2518173
   0.12605267  0.0063353  -0.53624907  0.85904184]
 [-1.11240377 -0.09175666 -1.94272646 -0.41686548  1.01047585 -1.2252658
  -0.69225156 -1.25205458 -0.67573108  1.1820192 ]
 [-1.5942987  -1.42081675 -0.36658592  0.4608317  -0.97003442 -0.09017658
   0.41002603 -1.43968852  0.07070815  0.33909859]
 [ 

2.7811236683595553

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
vec = np.random.randn(30)
np.mean(vec)

-0.2881581657056644

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
import numpy as np
mat = np.ones([5,5])
mat[1:-1, 1:-1] = 0

#mat[1:-1, 1:-1] = np.zeros([3,3])
mat

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
# np.concatenate  --> to complex but still valid

np.pad(mat,pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
print( 0 * np.nan                 )
print( np.nan == np.nan           )
print( np.inf > np.nan            )
print( np.nan - np.nan            )
print( np.nan in set([np.nan])    )   
print( 0.3 == 3 * 0.1             )    # flase, problem in comparison with floats due to rounding

print( type(0.3)         )
print( type(3 * 0.1)     )

nan
False
False
nan
True
False
<class 'float'>
<class 'float'>


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [27]:
mat = np.zeros([5,5])

for i in range(4):
    mat[i+1,i] = i+1

print(mat)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [36]:
# the pro way: (this build a matrix with  a specific diagonal)

mat = np.diag(1+np.arange(4),k=-1)
print(mat)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]]


In [42]:
x = np.arange(9).reshape(3,3)
print("Matrix: x")
print(x)

mat = np.diag(x)
print("Printing element from x's diagonal")
print(mat)

mat = np.diag(x, k=1)
print("Printing element from x's diagonal + 1")
print(mat)

mat = np.diag(x, k=-1)
print("Printing element from x's diagonal - 1")
print(mat)

Matrix: x
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Printing element from x's diagonal
[0 4 8]
Printing element from x's diagonal + 1
[1 5]
Printing element from x's diagonal - 1
[3 7]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [57]:
# chessboard style 

mat = np.zeros((8,8), dtype=int)
mat[1::2,::2] = 1
mat[::2,1::2] = 1

print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [66]:
mat = np.arange(6*7*8).reshape(6,7,8)

nx = 6
ny = 7 
nz = 8

print("mat[0,0,0]: {}".format(mat[0,0,0]))
print("mat[0,1,0]: {}".format(mat[0,1,0]))
print("mat[0,2,0]: {}".format(mat[0,2,0]))
print()

n = 100-1
z = n % nz

x = int(np.floor(n / (ny * nz)))
y = int(np.floor((n % (ny * nz)) / nz))

print (x, y , z)
print (mat[x,y,z])

mat[0,0,0]: 0
mat[0,1,0]: 8
mat[0,2,0]: 16

1 5 3
99


In [65]:
# the pro way

z = np.unravel_index(99, (6,7,8))
print(z)

(1, 5, 3)


Save your progress by commiting your work to Jovian

In [67]:
import jovian

<IPython.core.display.Javascript object>

In [68]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [74]:
x = np.array([[0,1],[1,0]])
np.tile(x,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [81]:
mat = np.random.randn(5,5)

print(np.mean(mat))
print(np.std(mat))
print("Close because it's just a few elements")


mat = np.random.randn(500,500)

print(np.mean(mat))
print(np.std(mat))
print("now we are talking")

-0.052122356278250945
0.9004901761568984
Close because it's just a few elements
-0.000335691301142513
1.001069266797396
now we are talking


In [82]:
# normalizing a random matrix

mat = np.random.rand(500,500)

print(np.mean(mat))
print(np.std(mat))
print()


mat = ( mat-np.mean(mat) )/ np.std(mat)
print(np.mean(mat))
print(np.std(mat))

0.5006880189086779
0.28897704097777177

-1.5003820408310275e-16
1.0000000000000002


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [100]:
color = np.dtype([("r", np.ubyte, 1 ),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

# TODO: pending analysis

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [102]:
mat_1 = np.random.randn(5,3)
mat_2 = np.random.randn(3,2)

result_1 = mat_1 @ mat_2
result_2 = np.matmul(mat_1, mat_2)

result_1 == result_2

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [125]:
x = np.floor(np.random.rand(10)*10).astype(int)
print(x)

x2 = np.arange(10)
print(x2)

x[(3 < x) & (x < 8)] *= -1
print(x)

x2[(3 < x2) & (x2 < 8)] *= -1
print(x2)


[7 1 6 6 6 5 1 3 9 2]
[0 1 2 3 4 5 6 7 8 9]
[-7  1 -6 -6 -6 -5  1  3  9  2]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [18]:
# 1. 9

print(sum(range(5),-1))     # ----> 9, ok!
# secod parameter is another number to sum

# from numpy import *
# print(sum(range(5),-1))     # -> 10 wtf
# this overrides sum function

import numpy as np
print(np.sum(range(5),-1))
# secod parameter is axis

print(np.sum([[1,2],[3,4]],0))
print(np.sum([[1,2],[3,4]],1))
print(np.sum([[1,2],[3,4]],-1))
# sumer check

9
10
[4 6]
[3 7]
[3 7]


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [41]:
Z = np.arange(9).astype(int)
print(Z)

print(Z**Z)                 # pow element-wise 
print(2 << Z)               # logical shift. base 2 multiplication
print(2 << Z >> 2)          # after previous step, each number is divided by 4
print(Z <- Z)               # bool comparison Z < -Z
print(1j*Z)                 # converting each number to the imaginary part of a complex number
print(Z/1/1)                # interesting... converting ints to floats because the division involved    
Z<Z>Z                       # error: 2nd operation: compearing bool with ints

[0 1 2 3 4 5 6 7 8]
[       1        1        4       27      256     3125    46656   823543
 16777216]
[  2   4   8  16  32  64 128 256 512]
[  0   1   2   4   8  16  32  64 128]
[False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```


In [44]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [53]:
x = np.random.uniform(-10,+10,10)
print(x)

x[x <0] = np.floor(x[x <0])
x[x >0] = np.ceil(x[x >0])
print(x)

print(np.copysign(np.ceil(np.abs(x)), x))

# More readable but less efficient
print(np.where(x>0, np.ceil(x), np.floor(x)))


[-7.08953612  7.22139107 -8.89378231  7.83660483  4.34563835  4.40093583
  6.15762025 -7.10372816  2.95704917 -6.27984883]
[-8.  8. -9.  8.  5.  5.  7. -8.  3. -7.]
[-8.  8. -9.  8.  5.  5.  7. -8.  3. -7.]
[-8.  8. -9.  8.  5.  5.  7. -8.  3. -7.]


In [77]:
N = 10**8

In [78]:
x = np.random.uniform(-10,+10,N)
print(len(x))

%time x[x <0] = np.floor(x[x <0])
%time x[x >0] = np.ceil(x[x >0])


100000000
Wall time: 2.32 s
Wall time: 2.21 s


In [79]:
x = np.random.uniform(-10,+10,N)
print(len(x))

%time x = np.copysign(np.ceil(np.abs(x)), x)

100000000
Wall time: 2.64 s


In [80]:
x = np.random.uniform(-10,+10,N)
print(len(x))

# More readable but less efficient
%time x=np.where(x>0, np.ceil(x), np.floor(x))

100000000
Wall time: 4.38 s


#### 30. How to find common values between two arrays? (★☆☆)

In [82]:
x1 = np.random.randint(0,10,10)
x2 = np.random.randint(0,10,10)
print(np.intersect1d(x1, x2))

[2 6 8]


Save your progress by commiting your work to Jovian

In [83]:
import jovian

<IPython.core.display.Javascript object>

In [84]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [88]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity (I'm crying hahahahaha)
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

np.arange(3) / 0

array([nan, inf, inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [93]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

False
nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [95]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2020-09-04
2020-09-05
2020-09-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [96]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [109]:
N = 10**8

In [110]:
A = np.ones(N)*1
B = np.ones(N)*2
C = np.ones(N)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5, ..., -1.5, -1.5, -1.5])

In [111]:
def funct_1():
    A = np.ones(N)*1
    B = np.ones(N)*2
    C = np.ones(N)*3
    np.add(A,B,out=B)
    np.divide(A,2,out=A)
    np.negative(A,out=A)
    np.multiply(A,B,out=A)

%time funct_1()

Wall time: 3.65 s


In [112]:
def funct_2():
    A = np.ones(N)*1
    B = np.ones(N)*2
    C = np.ones(N)*3
    A = ((A+B)*(-A/2))

%time funct_2()

Wall time: 5.16 s


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [118]:
#method 1
x = np.random.randn(10) * 10
print(x)
np.trunc(x)

[-22.5399474  -34.42516006  -4.47876689 -15.02363068   3.14744663
   9.49039001   4.10061709  -2.21330653  -7.86887024  -5.1919368 ]


array([-22., -34.,  -4., -15.,   3.,   9.,   4.,  -2.,  -7.,  -5.])

In [120]:
# method 2

print(x)
x.astype(int)


[-22.5399474  -34.42516006  -4.47876689 -15.02363068   3.14744663
   9.49039001   4.10061709  -2.21330653  -7.86887024  -5.1919368 ]


array([-22, -34,  -4, -15,   3,   9,   4,  -2,  -7,  -5])

In [121]:
# method 3


print(x)
x//1

[-22.5399474  -34.42516006  -4.47876689 -15.02363068   3.14744663
   9.49039001   4.10061709  -2.21330653  -7.86887024  -5.1919368 ]


array([-23., -35.,  -5., -16.,   3.,   9.,   4.,  -3.,  -8.,  -6.])

In [ ]:
# pending ... 
# could it be floor and ceil, but is another kind of aproximation like the last one

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [122]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [137]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


yield is a keyword that is used like return, except the function will return a generator.
3rd parameter of from iter is: --count-- int, optional
The number of items to read from iterable. The default is -1, which means all data is read.

In [136]:
# Generators
# Generators are iterators, a kind of iterable you can only iterate over once. Generators do not store all the values in memory, they generate the values on the fly:

mygenerator = (x*x for x in range(3))
for i in mygenerator:
    print(i)

for i in mygenerator:
    print(i)

0
1
4


it is just the same except you used () instead of []. BUT, you cannot perform for i in mygenerator a second time since generators can only be used once: they calculate 0, then forget about it and calculate 1, and end calculating 4, one by one

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [141]:
x = np.random.rand(10)

print(max(x))
print(min(x))

0.9736031416836449
0.015090965238816145


In [145]:
# still valid: linearly spaced samples
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [147]:
x = np.random.rand(10)
print(x)

print(np.sort(x))

print(x)

[0.53244266 0.92488065 0.06826649 0.44808376 0.4465072  0.92961973
 0.96181219 0.76231455 0.55963291 0.25239053]
[0.06826649 0.25239053 0.4465072  0.44808376 0.53244266 0.55963291
 0.76231455 0.92488065 0.92961973 0.96181219]
[0.53244266 0.92488065 0.06826649 0.44808376 0.4465072  0.92961973
 0.96181219 0.76231455 0.55963291 0.25239053]


Save your progress by commiting your work to Jovian

In [148]:
import jovian

In [149]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [154]:
N = 10 ** 9

x = np.random.rand(N)

%time np.add.reduce(x)
%time np.sum(x)

Wall time: 1.37 s
Wall time: 1.45 s


499995978.1594768

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [155]:
x = np.random.rand(10)

x == x

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [157]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 1 1 1 1]
[0 1 1 1 1]
False
False


numpy.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    rtolfloat - The relative tolerance parameter
    atolfloat - The absolute tolerance parameter (see Notes).
    equal_nanbool - 
    Whether to compare NaN’s as equal. If True, NaN’s in a will be considered equal to NaN’s in b in the output array.

#### 43. Make an array immutable (read-only) (★★☆)

In [159]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [180]:
cart = np.random.randint(0, 10, size=(5,2))

# visualizing a some coordinates
print(cart[:5,:])

def to_polar(x, y):
    mod = np.sqrt(x**2 + y**2) 
    angle = np.arctan(y / x)        # [rads]
    return [mod, angle]

for x, y in cart:
    print(to_polar(x,y))



[[5 0]
 [8 8]
 [0 7]
 [9 5]
 [8 2]]
[5.0, 0.0]
[11.313708498984761, 0.7853981633974483]
[7.0, 1.5707963267948966]
[10.295630140987, 0.507098504392337]
[8.246211251235321, 0.24497866312686414]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [190]:
x = np.random.randint(0,10,10)
print(x)

val = np.max(x)
idx = np.argmax(x)
print(val, idx)

x[x.argmax()] = 0
print(x)




[4 9 0 8 1 3 2 7 1 1]
9 1
[4 0 0 8 1 3 2 7 1 1]


In [201]:
# another method 
x = np.random.randint(0,10,10)
print(x)

idx = np.where(x == np.max(x))
print(idx[0])
x[idx[0]] = 0
print(x)

[2 5 4 6 7 8 4 8 6 1]
[5 7]
[2 5 4 6 7 0 4 0 6 1]
(array([4], dtype=int64),)
[2 5 4 6 0 0 4 0 6 1]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [206]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5, endpoint=True,),
                             np.linspace(0, 1, 5, endpoint=True))
print(Z)

print(Z['x'])
np.linspace(0,1,5)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [214]:
x = np.random.randn(5)
y = np.random.randn(5)
c =np.zeros((len(x), len(y)))

#for xi, yi, i in zip(x, y, range(len(c))):
#    c[i] = 1/(xi - yi)

for i in range(len(x)):
    for j in range(len(y)): 
        c[i,j] = 1/(x[i] - y[j])
print(c)
print(np.linalg.det(c))
print()

# interesting use of outer !
C = 1.0 / np.subtract.outer(x, y)
print(C)
print(np.linalg.det(C))

[[  0.7901747    0.67609977   0.92572179  -5.34176742   3.57868655]
 [  0.93176259   0.77714359   1.12621491  -2.63496199  11.4778975 ]
 [  1.78315151   1.29143309   2.66311533  -1.12114908  -2.35124854]
 [ -3.51318833 -14.06212706  -2.12790181  -0.57557647  -0.78693529]
 [  4.3745743    2.26181707  23.10060833  -0.81689121  -1.32010218]]
17476.96669803768

[[  0.7901747    0.67609977   0.92572179  -5.34176742   3.57868655]
 [  0.93176259   0.77714359   1.12621491  -2.63496199  11.4778975 ]
 [  1.78315151   1.29143309   2.66311533  -1.12114908  -2.35124854]
 [ -3.51318833 -14.06212706  -2.12790181  -0.57557647  -0.78693529]
 [  4.3745743    2.26181707  23.10060833  -0.81689121  -1.32010218]]
17476.96669803768


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [225]:
for dtype in [np.int8, np.int32, np.int64]:
   print("np.iinfo(dtype).min: {}".format(np.iinfo(dtype).min))
   print("np.iinfo(dtype).max: {}".format(np.iinfo(dtype).max))
   
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    #print("np.finfo(dtype).min: {}".format(np.iinfo(dtype).min, 'f'))
    #print("np.iinfo(dtype).max: {}".format(np.iinfo(dtype).max, 'f'))
    #print("np.iinfo(dtype).eps: {}".format(np.iinfo(dtype).eps))

np.iinfo(dtype).min: -128
np.iinfo(dtype).max: 127
np.iinfo(dtype).min: -2147483648
np.iinfo(dtype).max: 2147483647
np.iinfo(dtype).min: -9223372036854775808
np.iinfo(dtype).max: 9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [226]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

there is a lack of a good explanation for this exercise... 
if you have two vectors, you want to know which of the pair of elementes is the closest one

In [227]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

30


Save and commit your work.

In [228]:
import jovian

In [229]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [248]:
mat = np.zeros(10, [ ('position', [ ('x', float, 1),
                                    ('y', float, 1)
                                    ]),
                     ('color',    [ ('r', float, 1),
                                    ('g', float, 1),
                                    ('b', float, 1)
                                    ])
                    ])
print(mat)

print(mat.shape)
print(mat[0])
mat[0][0][0] = 1   # 1st element, 1st parameter (position), 1st coordinate
print(mat[0])
mat[0]['color']['r'] = 2
mat[0]['color'] = (2,3,4)
print(mat[0])

print(type(mat[0]))


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
(10,)
((0., 0.), (0., 0., 0.))
((1., 0.), (0., 0., 0.))
((1., 0.), (2., 3., 4.))
<class 'numpy.void'>


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [1]:
# I've no idea what is asking about...
import numpy as np

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
#import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
#import scipy.spatial

#Z = np.random.random((10,2))
#D = scipy.spatial.distance.cdist(Z,Z)
#print(D)

[[0.         0.44858243 0.89318133 0.25723835 0.62365714 0.86916848
  0.79275478 0.80902017 0.66806069 0.59906298]
 [0.44858243 0.         0.50132166 0.45879561 0.25750109 0.55021978
  0.34971306 0.36255338 0.26983935 0.27690672]
 [0.89318133 0.50132166 0.         0.77331205 0.59520699 0.18455036
  0.40614355 0.27010198 0.54608878 0.30049928]
 [0.25723835 0.45879561 0.77331205 0.         0.70019648 0.70220897
  0.79727902 0.76948078 0.72508203 0.47557381]
 [0.62365714 0.25750109 0.59520699 0.70019648 0.         0.70754653
  0.24605782 0.35164732 0.06388682 0.48296435]
 [0.86916848 0.55021978 0.18455036 0.70220897 0.70754653 0.
  0.55896338 0.42821013 0.66890839 0.28448076]
 [0.79275478 0.34971306 0.40614355 0.79727902 0.24605782 0.55896338
  0.         0.13612238 0.18268895 0.42511479]
 [0.80902017 0.36255338 0.27010198 0.76948078 0.35164732 0.42821013
  0.13612238 0.         0.29394229 0.34041619]
 [0.66806069 0.26983935 0.54608878 0.72508203 0.06388682 0.66890839
  0.18268895 0.29394

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [8]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
print(type(Z))
print(Z)

Y = Z.view(np.int32)
Y[:] = Z
print(Y)

print(hex(id(Z)))   # memory position of Z
print(hex(id(Y)))   # memory position of Y

<class 'numpy.ndarray'>
[54.57846  78.32195  78.76746  66.425224 51.15471  77.573814 37.35282
 14.859395 96.951416 70.57344 ]
[54 78 78 66 51 77 37 14 96 70]
0x1e5a427bad0
0x1e5a427bb20


a.view() is used two different ways:

a.view(some_dtype) or a.view(dtype=some_dtype) constructs a view of the array’s memory with a different data-type. This can cause a reinterpretation of the bytes of memory.

a.view(ndarray_subclass) or a.view(type=ndarray_subclass) just returns an instance of ndarray_subclass that looks at the same array (same shape, dtype, etc.) This does not cause a reinterpretation of the memory.

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [10]:
# working with files
with open("ex_54.txt", 'r') as fh:
    data = np.genfromtxt(fh, delimiter=",", dtype=np.int)
    print(data)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [17]:
# also interesting 

# generating a fake file
# Fake file
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [20]:
Z = np.arange(12).reshape(3,2,2)
for index, value in np.ndenumerate(Z):      # ndenumerate:  Return an iterator yielding pairs of 
    print(index, value)                     #               array coordinates and values.

print()
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7
(2, 0, 0) 8
(2, 0, 1) 9
(2, 1, 0) 10
(2, 1, 1) 11

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7
(2, 0, 0) 8
(2, 0, 1) 9
(2, 1, 0) 10
(2, 1, 1) 11


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [23]:
x = np.random.randn(5,5)
print(x)

[[ 0.56848255  0.35048751  0.75015222 -0.34606661  2.74643061]
 [-0.05812293  1.12024083  0.12907107 -0.83265863 -0.67630056]
 [ 0.1716029   0.63130114 -0.87618665 -0.01560609 -0.08734569]
 [-1.93062388 -0.23644223  1.291571    1.18559422 -0.68189664]
 [ 0.15588834 -1.95838733  1.61248647  1.31939837  0.90755527]]


In [44]:
# this is the correct answer
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [49]:
#X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
X, Y = np.meshgrid(np.linspace(0,10,10).astype(int), np.linspace(0,10,10).astype(int))

print(X)
print()
print(Y)

[[ 0  1  2  3  4  5  6  7  8 10]
 [ 0  1  2  3  4  5  6  7  8 10]
 [ 0  1  2  3  4  5  6  7  8 10]
 [ 0  1  2  3  4  5  6  7  8 10]
 [ 0  1  2  3  4  5  6  7  8 10]
 [ 0  1  2  3  4  5  6  7  8 10]
 [ 0  1  2  3  4  5  6  7  8 10]
 [ 0  1  2  3  4  5  6  7  8 10]
 [ 0  1  2  3  4  5  6  7  8 10]
 [ 0  1  2  3  4  5  6  7  8 10]]

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4]
 [ 5  5  5  5  5  5  5  5  5  5]
 [ 6  6  6  6  6  6  6  6  6  6]
 [ 7  7  7  7  7  7  7  7  7  7]
 [ 8  8  8  8  8  8  8  8  8  8]
 [10 10 10 10 10 10 10 10 10 10]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [50]:
n = 10  # dimension
p = 3   # N elements to place

Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [8]:
import numpy as np
x = np.random.rand(4,6)*10
print(x)
print()

mean = x.mean(axis=1, keepdims=True)
print(mean.shape)
print(mean)
print()

print(np.mean(x[0,:]))
print(np.mean(x[1,:]))
print()

x -= np.mean(x, axis=1, keepdims=True)
print(x)

[[0.67995542 0.6290281  2.84860139 4.82382184 9.54423484 7.60695927]
 [7.44928023 3.7518681  4.64512364 0.04191091 5.85133005 8.52227594]
 [7.384609   6.24307571 0.62529728 1.32913924 1.71133788 2.0070744 ]
 [1.56617647 2.68697449 3.8875445  2.7917876  5.61945087 5.51248633]]

(4, 1)
[[4.35543348]
 [5.04363148]
 [3.21675559]
 [3.67740338]]

4.355433476175201
5.043631479987664

[[-3.67547805 -3.72640537 -1.50683209  0.46838836  5.18880136  3.25152579]
 [ 2.40564875 -1.29176338 -0.39850784 -5.00172057  0.80769857  3.47864446]
 [ 4.16785342  3.02632012 -2.5914583  -1.88761635 -1.50541771 -1.20968118]
 [-2.11122691 -0.99042889  0.21014113 -0.88561578  1.94204749  1.83508296]]


#### 59. How to sort an array by the nth column? (★★☆)

In [15]:
# this is the same case than a shopping list like

# argsort: Returns the indices that would sort an array.

Z = np.random.randint(0, 10, (3,3))
print(Z)
print()

col = 1
print( Z[ Z[:, col].argsort() ] )
print()


[[6 5 2]
 [6 7 0]
 [4 6 4]]

[[6 5 2]
 [4 6 4]
 [6 7 0]]



#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [32]:
# any:  Test whether any array element along a given axis evaluates to True. 
#       Returns single boolean unless axis is not None

Z = np.random.randint(0,3,(3,10))
Z[:,2] = 0
print(Z)
print()

print(Z.any(axis=0))
print()

print((~Z.any(axis=0)).any())

[[2 2 0 1 1 0 2 2 2 0]
 [2 2 0 1 1 0 2 1 2 0]
 [2 0 0 2 0 0 0 2 1 1]]

[ True  True False  True  True False  True  True  True  True]

True



Save and commit your work.

In [33]:
import jovian

<IPython.core.display.Javascript object>

In [34]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 61. Find the nearest value from a given value in an array (★★☆)

In [45]:
x = np.random.randint(0,100, 15)
print(x)

val = 35
print(x[np.argmin(np.abs(x-val))])
print()

x = np.random.randint(0,100, (4,15))
print(x)
val = 25
print(x.flat[np.argmin(np.abs(x-val))])

[65 28 81 28 56 68 44 68 14 15 57 60 57 26  3]
28

[[24 24 90 31  3 77 18 28 16 38 62 74 22 60 88]
 [ 8 36 30 50 19  1 42 26 24 22 53 21 28  4 57]
 [ 7 47 18  0 84 48 27 87 91 53 50 16 33 78 84]
 [ 3 90 44 34  6 58 67 84 36  5 84 75 13 48 34]]
24


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [49]:
# TODO: analyze better

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A)
print()
print(B)
print()

it = np.nditer([A, B, None])
for x,y,z in it: z[...] = x + y

print(it.operands[2])

[[0]
 [1]
 [2]]

[[0 1 2]]

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [61]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

Z = NamedArray(np.arange(10))
print (Z.name)

range_10
no name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

for each occurrence on the second vector add 1 to the first vector using the value of the second vector as the index of the first one:
```python
          v1[ v2[i] ] += 1   
```
with i=0.. len(v2)

In [84]:
Z = np.ones(10)
print(Z)
#I = np.random.randint(0,len(Z),20)
# making I constant to make the repeatable
I = [3, 1, 0, 4, 5, 9, 1, 5, 3, 1, 5, 3 ,0, 3,8, 8, 1, 4, 4, 2]
print(I)
print()

bins = np.bincount(I, minlength=12)
print(bins)
bins = np.bincount(I, minlength=10)
print(bins)
print()

Z1 = Z + np.bincount(I, minlength=len(Z))
print(Z1)
Z2 = Z + np.bincount(I, minlength=1)
print(Z2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3, 1, 0, 4, 5, 9, 1, 5, 3, 1, 5, 3, 0, 3, 8, 8, 1, 4, 4, 2]

[2 4 1 4 3 3 0 0 2 1 0 0]
[2 4 1 4 3 3 0 0 2 1]

[3. 5. 2. 5. 4. 4. 1. 1. 3. 2.]
[3. 5. 2. 5. 4. 4. 1. 1. 3. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [85]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

# numpy.bincount(x, weights=None, minlength=0)
# If weights is specified the input array is weighted by it, 
# i.e. if a value n is found at position i, out[n] += weight[i] instead of out[n] += 1.

# TODO: ni idea como funciona

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [2]:
import numpy as np
w,h = 20,20

bits = 8

img = np.random.randint(0, 2**bits, (h,w,3)).astype(np.ubyte)

F = img[...,0] * 256 * 256 + img[...,1] * 256 + img[...,2]

n = len(np.unique(F))
print(n)
print(F.shape)
#print(np.unique(F))

print(256*256*256)

396
(20, 20)
16777216


In [104]:
h=2
w=3

img = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
print(type(img[0,0,0]))
print(img.shape)
print()

print(img)
print()

print(img[0,...])
print(img[...,0])


<class 'numpy.uint8'>
(2, 3, 3)

[[[0 0 1]
  [1 1 0]
  [0 1 1]]

 [[1 0 0]
  [1 0 1]
  [1 1 0]]]

[[0 0 1]
 [1 1 0]
 [0 1 1]]
[[0 1 0]
 [1 1 1]]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [5]:
x = np.random.rand(4,4,4,4)

s = np.sum(x, axis=(-2,-1))
print(s)


[[ 8.57533482  7.67772492  6.6464955   7.76397838]
 [ 6.66720346  6.56879743 10.19102365  8.15644424]
 [ 8.918444    8.04990326  6.59074499  9.69468555]
 [ 8.2884057   9.50909508  8.26411434  5.5284602 ]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [9]:
# TODO: pending...
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

print(D[:10])
print(D.shape)

D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print("means:")
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.34568004 0.46382073 0.84586101 0.05587356 0.27295365 0.2587523
 0.77853552 0.97270198 0.19189911 0.30085829]
(100,)
means:
[0.61541838 0.30317156 0.46077945 0.51402387 0.50290878 0.33185854
 0.43839138 0.60426293 0.41306925 0.57347672]
0    0.615418
1    0.303172
2    0.460779
3    0.514024
4    0.502909
5    0.331859
6    0.438391
7    0.604263
8    0.413069
9    0.573477
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [13]:
# dot product for 2D

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
y = np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.16480846, 1.62881935, 1.61416087, 1.81135963, 1.96887561])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [14]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Save and commit your work

In [15]:
import jovian

<IPython.core.display.Javascript object>

In [16]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [19]:
A = 3*np.ones((2,2,3))
B = 2*np.ones((2,2))
print(A * B[:,:,None])

# no tiene sentido esto, sería interesante ver una interpetación real de esto

[[[6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]]]


#### 72. How to swap two rows of an array? (★★★)

In [24]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [25]:
A = np.arange(25).reshape(5,5)
A[[0,2]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [27]:
#swapping two columns

A = np.arange(25).reshape(5,5)
A[:,[0,1]] = A[:,[1,0]]
print(A)

[[ 1  0  2  3  4]
 [ 6  5  7  8  9]
 [11 10 12 13 14]
 [16 15 17 18 19]
 [21 20 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [31]:
# TODO
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(12, 48) (12, 78) (14, 69) (14, 84) (20, 88) (20, 99) (29, 62) (29, 79)
 (32, 40) (32, 58) (33, 34) (33, 87) (34, 87) (38, 78) (38, 82) (40, 58)
 (42, 55) (42, 98) (43, 45) (43, 64) (43, 81) (43, 82) (45, 82) (48, 78)
 (55, 98) (62, 79) (64, 81) (69, 84) (78, 82) (88, 99)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [32]:
# TODO
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [48]:
a = np.linspace(1,10,10)
print(a)
print(a.cumsum())   # cumulative sum of elements along a given axis
print()

def moving_average(a, n=3) :
    """ 
    This is a beautiful masterpiece
    """
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(10)
print(Z)

avgs = moving_average(Z, n=4)
print(len(avgs))
print(avgs)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  3.  6. 10. 15. 21. 28. 36. 45. 55.]

[0 1 2 3 4 5 6 7 8 9]
7
[1.5 2.5 3.5 4.5 5.5 6.5 7.5]


In [47]:
# debuging the function and auto contained explanation thru console output
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    print("------")
    print(ret)
    print(ret[n:])
    print(ret[:-n])
    print(ret[n:]-ret[:-n])
    print(ret)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(10)
print(Z)

avgs = moving_average(Z, n=4)
print("----")
print(len(avgs))
print(avgs)

[0 1 2 3 4 5 6 7 8 9]
------
[ 0.  1.  3.  6. 10. 15. 21. 28. 36. 45.]
[10. 15. 21. 28. 36. 45.]
[ 0.  1.  3.  6. 10. 15.]
[10. 14. 18. 22. 26. 30.]
[ 0.  1.  3.  6. 10. 15. 21. 28. 36. 45.]
----
7
[1.5 2.5 3.5 4.5 5.5 6.5 7.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [51]:
# hint: numpy.lib.stride_tricks.as_strided
# beautiful warning from docs: This function has to be used with extreme care, see notes.
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
    
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [57]:
Z = np.random.randint(0,2,10)
print(Z)
np.logical_not(Z, out=Z)
print(Z)
print()

Z = np.random.uniform(-1.0,1.0,10)
print(Z)
np.negative(Z, out=Z)
print(Z)

[1 1 0 0 0 0 0 0 0 0]
[0 0 1 1 1 1 1 1 1 1]

[-0.85006847  0.51908504 -0.0635212  -0.36763693 -0.14019119  0.47036782
  0.21806036  0.49934278  0.10948809  0.60667783]
[ 0.85006847 -0.51908504  0.0635212   0.36763693  0.14019119 -0.47036782
 -0.21806036 -0.49934278 -0.10948809 -0.60667783]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [58]:
# what kind of distance ¿?  --- no hint
# NP: supongo que es la deducción matemática pero no pienso perder tiempo deducir algo que se puede hacer de mil maneras distinatas...

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

# TODO: ...

[ 5.19472307  2.6995979  13.65655311 10.39584757  6.76470885  7.46004833
  9.85016664 14.90481259  6.6727541   4.42820387]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10, 10, (10,2))
p = np.random.uniform( -10, 10, (10,2))

# the easiest way is with a compression list
print(np.array([distance(P0,P1,p_i) for p_i in p]))

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [64]:

Z = np.random.randint(0,10,(10,10)) # raw data 
shape = (5,5)                       # shape of the pattern
fill  = 0                           # default fill element
position = (1,1)                    # center of the subpart

R = np.ones(shape, dtype=Z.dtype)*fill      # memory to alocate the subpart (pattern)
P  = np.array(list(position)).astype(int)   # position of the subpart
Rs = np.array(list(R.shape)).astype(int)    # R (subpart) shape
Zs = np.array(list(Z.shape)).astype(int)    # raw data shape
print(P)
print(Rs)
print(Zs)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
print()
print(R_start)
print(R_stop)
print(Z_start)
print(Z_stop)

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
print()
print(R_start)
print(R_stop)
print(Z_start)
print(Z_stop)

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


[1 1]
[5 5]
[10 10]

[0 0]
[5 5]
[-1 -1]
[4 4]

[1, 1]
[5, 5]
[0, 0]
[4, 4]
[[2 6 8 6 1 6 5 7 8 6]
 [8 5 6 2 6 4 7 6 8 4]
 [5 7 5 0 1 3 2 9 6 4]
 [7 2 3 3 7 6 9 0 5 9]
 [6 3 1 0 1 1 1 7 2 9]
 [4 9 0 6 6 8 4 0 7 3]
 [1 4 0 1 2 5 1 5 5 1]
 [0 1 8 1 8 6 8 0 4 2]
 [8 9 9 7 6 2 3 7 4 3]
 [5 4 1 4 8 2 4 5 7 3]]
[[0 0 0 0 0]
 [0 2 6 8 6]
 [0 8 5 6 2]
 [0 5 7 5 0]
 [0 7 2 3 3]]


Save and commit your work.

In [61]:
import jovian

In [63]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "leosf/week3-ntk2-100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises


'https://jovian.ml/leosf/week3-ntk2-100-numpy-exercises'

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [66]:
x = np.arange(1, 15, dtype=np.uint32)
y = stride_tricks.as_strided(x, (11,4), (4,4))
print(y)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [68]:
x = np.random.uniform(0, 1, (20,20))
U, S, V = np.linalg.svd(x)              # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

20


#### 83. How to find the most frequent value in an array?

In [69]:
x = np.random.randint(0,20,200)
print(np.bincount(x).argmax())

16


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [70]:
Z = np.random.randint(0, 5, (10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 4 2]
   [2 4 4]
   [3 1 1]]

  [[4 2 2]
   [4 4 2]
   [1 1 3]]

  [[2 2 3]
   [4 2 0]
   [1 3 4]]

  [[2 3 2]
   [2 0 2]
   [3 4 0]]

  [[3 2 2]
   [0 2 1]
   [4 0 4]]

  [[2 2 1]
   [2 1 2]
   [0 4 1]]

  [[2 1 1]
   [1 2 3]
   [4 1 2]]

  [[1 1 0]
   [2 3 0]
   [1 2 1]]]


 [[[2 4 4]
   [3 1 1]
   [1 3 1]]

  [[4 4 2]
   [1 1 3]
   [3 1 1]]

  [[4 2 0]
   [1 3 4]
   [1 1 1]]

  [[2 0 2]
   [3 4 0]
   [1 1 0]]

  [[0 2 1]
   [4 0 4]
   [1 0 1]]

  [[2 1 2]
   [0 4 1]
   [0 1 2]]

  [[1 2 3]
   [4 1 2]
   [1 2 3]]

  [[2 3 0]
   [1 2 1]
   [2 3 0]]]


 [[[3 1 1]
   [1 3 1]
   [3 2 3]]

  [[1 1 3]
   [3 1 1]
   [2 3 1]]

  [[1 3 4]
   [1 1 1]
   [3 1 2]]

  [[3 4 0]
   [1 1 0]
   [1 2 3]]

  [[4 0 4]
   [1 0 1]
   [2 3 1]]

  [[0 4 1]
   [0 1 2]
   [3 1 1]]

  [[4 1 2]
   [1 2 3]
   [1 1 3]]

  [[1 2 1]
   [2 3 0]
   [1 3 1]]]


 [[[1 3 1]
   [3 2 3]
   [0 4 4]]

  [[3 1 1]
   [2 3 1]
   [4 4 3]]

  [[1 1 1]
   [3 1 2]
   [4 3 2]]

  [[1 1 0]
   [1 2 3]
   [3 2 4]]

  [[1 0 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [3]:
import numpy as np

In [4]:
class Symetric(np.ndarray):
    """
    Symetric class of a 2D array. When a alement of the array is modified such as Zi,j, also Zj,i takes the same value.
    """
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
# observe what happens with random
S[2,3] = 42
print(S)

[[ 8  7 12  5  8]
 [ 7  7  1  8  6]
 [12  1  0 42  6]
 [ 5  8 42  1  5]
 [ 8  6  6  5  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [5]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [15]:
x = np.random.rand(16,16)

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                    np.arange(0, Z.shape[1], k), axis=1)

print(np.arange(0, Z.shape[0], k))
print()

print(S)
print()

k = 5
print(np.arange(0, Z.shape[0], k))
print()
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)



[ 0  4  8 12]

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]

[ 0  5 10 15]

[[25. 25. 25.  5.]
 [25. 25. 25.  5.]
 [25. 25. 25.  5.]
 [ 5.  5.  5.  1.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

At each step in time, the following transitions occur:
* Any live cell with fewer than two live neighbours dies, as if by underpopulation.
* Any live cell with two or three live neighbours lives on to the next generation.
* Any live cell with more than three live neighbours dies, as if by overpopulation.
* Any dead cell with exactly three live neighbours becomes a live cell, as if by reproduction.

These rules, which compare the behavior of the automaton to real life, can be condensed into the following:
* Any live cell with two or three live neighbours survives.
* Any dead cell with three live neighbours becomes a live cell.
* All other live cells die in the next generation. Similarly, all other dead cells stay dead.

The initial pattern constitutes the seed of the system.

In [23]:
[0, 1, 0] | [1, 0 , 0]

TypeError: unsupported operand type(s) for |: 'list' and 'list'

In [28]:
x = np.ones([2,3,5])

x[0,...] = 0

x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [29]:

def iterate(Z):
    """
    Iterate function to calculate 
    :param Z: complete map
    """
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    # esta es la suma de la superposición de posiciones desplazadas, con lo cual realmente se estarían contado la cantidad de vecinos para una posición específica (x,y)

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    
    return Z


# 2D map with automatas. Two posible values allowed {0,1}. Size 50x50
Z = np.random.randint(0, 2, (15,15))


for i in range(100): 
    Z = iterate(Z)

print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

In [20]:
import jovian

In [21]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Save and commit your work

In [22]:
import jovian

In [ ]:
#jovian.commit(user='leosf', filename='100-numpy-exercises.ipynb', project='week3_ntk2_100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100