In [2]:
import numpy as np
Z = np.ones(10)
print(Z)
#I = np.random.randint(0,len(Z),20)
# making I constant to make the repeatable
I = [3, 1, 0, 4, 5, 9, 1, 5, 3, 1, 5, 3 ,0, 3,8, 8, 1, 4, 4, 2]
print(I)
print()

bins = np.bincount(I, minlength=12)
print(bins)
bins = np.bincount(I, minlength=10)
print(bins)
print()

Z1 = Z + np.bincount(I, minlength=len(Z))
print(Z1)
Z2 = Z + np.bincount(I, minlength=1)
print(Z2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3, 1, 0, 4, 5, 9, 1, 5, 3, 1, 5, 3, 0, 3, 8, 8, 1, 4, 4, 2]

[2 4 1 4 3 3 0 0 2 1 0 0]
[2 4 1 4 3 3 0 0 2 1]

[3. 5. 2. 5. 4. 4. 1. 1. 3. 2.]
[3. 5. 2. 5. 4. 4. 1. 1. 3. 2.]
